# Generated by Django 5.2.1 on 2025-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Filme', 'Filme'), ('Série', 'Série')], max_length=10)),
                ('genero', models.CharField(max_length=100)),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('sinopse', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
